### PR TITLE
Fix phpBB error when quoting some posts

### LINKED ISSUE #15: PHP warning when quoting some posts
Since upgrading this extension to v1.2.0,  some posts cannot be quoted, giving a phpBB error of: [phpBB Debug] PHP Warning: in file [ROOT]/vendor/s9e/text-formatter/src/Utils.php on line 76: DOMDocument::loadXML(): EntityRef: expecting ';' in Entity, line: 8

An example of a post which exhibits the problem is:```
 [quote=crapday69 post_id=555947 time=1509899549 user_id=25001]
 give you "[youtube][/youtube]" in the text box. "https://www.youtube.com/watch?time_continue=6&v=[color=#8000FF]lmHUUXweR3I[/color]&ab_channel=GaryGordon". f the [youtube][/youtube] to give you.....  [attachment=0]youtube code.jpg[/attachment]    That should embed the Youtube video.```

You would need to reconstruct this with a real attached image to see the problem.

This was found on a system running phpBB v3.2.7 and php V7.1.32

I have managed to fix the issue and will create a PR.

### PR DESCRIPTION
**Pull request by v12mike**
The change to the $preg= line is just good practice to avoid using as delimiters a character that occurs in the regex string.

The real fix is to change the '&' in the reformatted link to be an html entitiy so that it does not upset the s9e renderer.

Fix #15

### CODE REVIEW

**Comment by 3D-I** [comment]
#15 

> I have now worked out how to reproduce the bug.
> 
> 1. Create a post containing an attachment.
> 2. Place [quote] ... [/quote] tags around the attachment tags by editing the original post and submit.
> 3. Quote the post using the quote button on the viewtopic form.


Thanks for reporting this issue Mike,
I went ahead and truly tested the fix proposed.

It works fine if the attachments are placed INLINE, while if the attachments aren't placed and there is a quoted test in the post like
`[quote]test[/quote]`



immagine

And we quote this post then the error is still there with a different trace.

`[ROOT]/vendor/s9e/text-formatter/src/Utils.php on line 76: DOMDocument::loadXML(): Extra content at the end of the document in Entity, line: 2`

And yes, I edited the `&` to be `&amp;` also in the related codeline for NO INLINE attachs.

immagine

**Comment by 3D-I** [comment]
I have already did it, see my above last picture.

**Comment by 3D-I** [comment]
Replacing the regexp works fine in bot cases

`$preg = '/<ATTACHMENT filename="[^"]*?" index="(' . implode('|', array_keys($rows)) . ')">.*?<\/ATTACHMENT>/';`

File: event/main_listener.php [hunk 1]
```diff
@@ -210,7 +210,7 @@ function($match) use (&$rows, $img) {
 						/* Use relative path for the sake of future's proof */
 						$link = $this->root_path . 'download/file.' . $this->php_ext . '?id=' . (int) $row['attach_id'];
 
-						$text .= "\n[url={$link}&mode=view]{$img['open']}{$link}{$img['close']}[/url]";
+						$text .= "\n[url={$link}&amp;mode=view]{$img['open']}{$link}{$img['close']}[/url]";
```
Comment (3D-I) [inline event/main_listener.php]: Replace this line with

```
						/* Strip the closing XML tag */
						$text = substr($text, 0, strlen($text) - 4);

						/* Add image link*/
						$text .= "\n[url={$link}&amp;mode=view]{$img['open']}{$link}{$img['close']}[/url]";

						/* Add back the closing XML tag */
						$text .= '</r>';
```

And test pls, here is fixed.

Comment (3D-I) [reply event/main_listener.php]: immagine

**Comment by v12mike** [comment]
Yes that works for me also.  
Thanks for your fast response

**Comment by 3D-I** [comment]
You can commit those changes if you like. Thanks for your contribution. :+1:
